wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
beta:
  value:
  - 0.7
  - 0.8
  - 0.9
beta1:
  value: 0.9
beta2:
  value: 0.9999
criterion:
  value: mse
decay:
  value: 5.0e-06
epochs:
  value:
  - 5
  - 10
epsilon:
  value: 1.0e-08
hidden_layers:
  value: 5
input_size:
  value: 784
learning_rate:
  value: 0.001
neurons:
  value: 32
optimizer:
  value: momentum
output_activation:
  value: softmax
output_size:
  value: 10
weight_initialization:
  value: random
